export * from './Nav/Nav';
export * from './Outstaff/Outstaff';
export * from './Hero/Hero';
export * from './Partners/Partners';
export * from './Comparison/Comparison';
export * from './Features/Features';
export * from './SpecialistCards/SpecialistCards';
export * from './Cooperation/Cooperation';
export * from './FeedBack/FeedBack';
